[package]
name = "detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.83.0"
linfa-clustering = "0.7.0"
linfa = "0.7.0"
simpler_timer = "0.2.0"
